# Configuration file version
apiVersion: 1

datasources:
- name: prometheus
  uid: prometheus
  type: prometheus
  url: http://prometheus:9090
  interval: 15s
- name: Jaeger
  type: jaeger
  access: proxy
  url: http://jaeger:16686
  isDefault: false