groups:
  - name: example
    rules:
      - alert: PeriodicTestAlert
        expr: minute() < 15
        # for: 1m
        labels:
          severity: warning
          service: my-service
        annotations:
          summary: "Test Alert"
          description: "Alerts for the first 15 minutes of each hour"
          
