# To Launch Grafana:
# - `docker-compose up -d`
# - Navigate to `http://localhost:3000` in a browser and log in with the default credentials (admin/admin)
#
# To stop the containers: `docker-compose down`
#
# To stop the containers and discard state: `docker-compose down -v`

networks:
  monitoring:
    driver: bridge

services:
  grafana: 
    image: grafana/grafana-oss
    networks:
      - monitoring
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
  metrics-generator:
    build:
      context: ./metrics-generator
    ports:
      - 8000:8000
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

volumes:
  grafana-data:
    driver: local
  prometheus_data:
    driver: local